### ISSUE TITLE
Add backup files

### ISSUE THREAD

**Issue by magixus** [leonovk/wg-rest-api#100]
**Is your feature request related to a problem? Please describe.**
I accidently deleted the clients when was developing a UI and I could revert back 

**Describe the solution you'd like**
Idialy backup wg config files after each update / delete operation 

**Describe alternatives you've considered**
a workaround is to cron job periodic backups

**Comment by leonovk** [comment]
@magixus Great idea. I'll do it soon.

**Comment by magixus** [comment]
Thanks @leonovk great works here
