### ISSUE TITLE
patch update data

### ISSUE THREAD

**Issue by Kazykan** [leonovk/wg-rest-api#107]
```
curl --location --request PATCH 'http://net.ya.ru:3000/api/clients/5' \
--header 'Authorization: Bearer 123' \
--header 'Content-Type: application/json' \
--data '{
"enable": true,
  "data": {
    "telegram_id" : "111111",
      "date_created" : "22-14-2023",
      "expiry_date" : "10.12.2024"
  }
}'
```

I add all the fields in the following "data" query.
If I leave only "expiry_date", it will erase all the other fields in the data  "telegram_id" and  "date_created"
How to make a partial change in "data"

**Comment by leonovk** [comment]
@Kazykan Yes, you are right, this overwrites the data, I will make a certificate of this

**Comment by leonovk** [comment]
@Kazykan Made an edit, now if you send any attributes in the data field, they will not overwrite themselves but will merge. However, if you intentionally send an empty object, it will erase all attributes in the data field. The update will be included in the next release, update your image.

**Comment by leonovk** [comment]
https://github.com/leonovk/wg-rest-api/releases/tag/v2.1.1
