### ISSUE TITLE
Add client status to the API

### ISSUE THREAD

**Issue by magixus** [leonovk/wg-rest-api#111]
**Is your feature request related to a problem? Please describe.**
The webhook event is already detecting the status of each client ,(connected / disconnected) would love to see this also via API 
The reason am asking for this is to be able to filter the ones that are disconnected for long period of time and be able to assign these clients to different devices if needed. 

I have created a UI to see all my clients so having this feature will make sense to everything related to WG 

![image](https://github.com/user-attachments/assets/fcf99106-d321-42ab-b862-77225a9cd8a1)

**Describe the solution you'd like**
I want to be able to see client status within API. ideally another field called `status` with values `connected / disconnected` 

**Describe alternatives you've considered**
Am using the webhook events but wanna see everything in my API/UI

**Comment by leonovk** [comment]
@magixus Why can't you filter users who have been disconnected for a long time by the last_online field?

**Comment by magixus** [comment]
I am planning to do that in addition to `status`

`Status should give quick overview of the peers that are offline/online. 

I thought the event handler is already doing that, and it's already adding details  to `wg0_events.json` thus instead of adding another computation layer in the frontend I was thinking maybe having this in the API would make sense  isn't it? 

![image](https://github.com/user-attachments/assets/388bced6-3eeb-49da-821b-802216ca3e1c)

**Comment by leonovk** [comment]
@magixus Yes, but the thing is that these events do not reflect the current status of the client, they simply indicate the fact of the event. Therefore, it seems to me that reusing them would not be entirely correct. Unfortunately, WireGuard does not provide information on the current connection status of the client. All that is available is the volume of transmitted traffic and the time of the last handshake. All this is already in the API. By the way, webhook events work based on this information.

**Comment by magixus** [comment]
great @leonovk and thanks for the explanation. I'll work on the frontend part to compute status based on last online.
