### ISSUE TITLE
Feature Request: Connection Event Webhook

### ISSUE THREAD

**Issue by takielias** [leonovk/wg-rest-api#45]
**Is your feature request related to a problem? Please describe.**

First, I'd like to thank you for this awesome API! It has been incredibly useful for managing WireGuard servers.

However, I'm always frustrated when I am unable to receive real-time notifications for client connection events (connect/disconnect) on my WireGuard server. This makes it difficult to monitor client activity and respond promptly to changes in connection status. Additionally, managing multiple device connections for a single client without real-time updates is challenging.

**Describe the solution you'd like**

I would like to request the implementation of webhooks for client connection events. This feature would allow administrators to configure a URL that the WireGuard REST API can call whenever a client connects or disconnects from the server. The webhook should include information about the client, the event type (connect or disconnect), and support for multiple device connections per client.

**Describe alternatives you've considered**

I have considered implementing a polling mechanism to check the status of clients periodically, but this approach is inefficient and does not provide real-time notifications. A webhook would be a much more effective solution for receiving timely updates, especially when dealing with multiple devices per client.

**Additional context**

Implementing this feature would greatly enhance the ability to monitor and manage client connections on the WireGuard server. Real-time notifications allow administrators to respond quickly to connection issues, unauthorized access, or other critical events. Moreover, it would simplify the management of multiple device connections for a single client.

Thank you for considering this feature request.

**Comment by leonovk** [comment]
I didn't quite understand your request, do you want webhooks to trigger when a new key is created/deleted on the server? Or when an existing client connects via a key? If the latter, then Wireguard itself does not support such notifications and they will have to be implemented using a constant polling method.

**Comment by takielias** [comment]
@leonovk 

I want webhooks to trigger when an existing client connects or disconnects. I understand WireGuard doesn't support these notifications directly. Implementing it with a constant polling method would be great. This feature would help monitor client activity in real-time and manage multiple device connections for a single client more efficiently.

**Comment by leonovk** [comment]
@takielias I think it can be implemented. It will work through Scheduled Tasks. You will need to install Kronoba on your server and set the frequency of the poll

**Comment by takielias** [comment]
@leonovk I can set this up myself, but I would love to get this feature from your awesome API. It would be really helpful for monitoring client activity in real-time and managing multiple device connections more efficiently.

**Comment by leonovk** [comment]
@takielias Yes, I have already created a branch for developing this feature. I have taken it into work. Thank you. I would be grateful if you put a star on the project

**Comment by takielias** [comment]
@leonovk Thank you so much. I have also put a ⭐& Waiting for the release.
