### ISSUE TITLE
Traffic and last online as a numeric data type

### ISSUE THREAD

**Issue by ivaneliseeff** [leonovk/wg-rest-api#86]
Hi. 
Let me ask briefly - is it possible to get such parameters as last_online and traffic as numbers? 

last_online as timestamp, traffic in bytes. 
I think it is acceptable to specify this in .env to avoid compatibility problems for those users who already use your solution and have implemented some metrics based on the values that are currently given.

**Comment by leonovk** [comment]
@ivaneliseeff hello, yes that sounds like a good idea, i thought about it myself. But i don't think supporting both is a good idea, so i guess this change can be added in a major version update.

**Comment by leonovk** [comment]
If anyone else needs this change, please like this or any other comment in this issue. This will help these changes get into the current version faster.

**Comment by BeppeMarnell** [comment]
> Hi. Let me ask briefly - is it possible to get such parameters as last_online and traffic as numbers?
> 
> last_online as timestamp, traffic in bytes. I think it is acceptable to specify this in .env to avoid compatibility problems for those users who already use your solution and have implemented some metrics based on the values that are currently given.

I Agree with this. I am currently looking at integrating this application with a cloud service and translating these values into an interpretable format would be a lot beneficial.
