### ISSUE TITLE
docker host network mode

### ISSUE THREAD

**Issue by ivaneliseeff** [leonovk/wg-rest-api#88]
How about support for network_mode: “host” ?

I'm trying to transfer traffic to local dns in pi-hole, and ideally to drive traffic to local proxy. 
Now I managed to get traffic to DNS, but it does not show IP addresses from which users connect, and there are no great opportunities for control, in pi-hole only ip address of the container is visible. 

I was able to do this by running wireguard as a service, but I would like to have the same convenient user control that is presented in your product.

**Comment by leonovk** [comment]
@ivaneliseeff I didn't quite understand what you're proposing to do. Are you proposing to create a mode in which the application instance would work inside the docker, but with the wireguard server running on the host outside the docker?

**Comment by leonovk** [comment]
In general, you can theoretically run the application in standalone mode. Without docker at all. By installing all the necessary dependencies. Then the application will work with your wireguard server directly.

**Comment by ivaneliseeff** [comment]
> In general, you can theoretically run the application in standalone mode. Without docker at all. By installing all the necessary dependencies. Then the application will work with your wireguard server directly.

I tried it. 
When asdf spent the second hour compiling dependencies for the installation, I gave up and abandoned it :))))

**Comment by leonovk** [comment]
The main snag in implementing your idea is that the application inside the docker container will need to somehow reboot from within and interact with your wireguard server on the host.
