### ISSUE TITLE
Request docker image for arm64

### ISSUE THREAD

**Issue by BeppeMarnell** [leonovk/wg-rest-api#91]
Hello, thank you for keeping up with this project.
I have a little request. Could you build this package for arm64? I don't have a x86 machine at the moment and for hobbyists, the Pi may be the way to go.

These are the steps to build an arm64 image with a raspberryPi:
1. Downloading this repo
2. Building it for arm64 ```docker build --platform linux/arm64 -t leonovk/wg-rest-api:arm64 .```
3. Running it ```docker run .... leonovk/wg-rest-api:arm64 ``` (like explained in the README)

All this works well so far for arm64.

**Comment by leonovk** [comment]
Okay, I'll take care of it.

**Comment by leonovk** [comment]
made an image. You can use it by specifying the tag explicitly. `docker run .... leonovk/wg-rest-api:1.9.9-arm64`

**Comment by BeppeMarnell** [comment]
Awesome!
