### ISSUE TITLE
Increase the amount of connected devices

### ISSUE THREAD

**Issue by BeppeMarnell** [leonovk/wg-rest-api#99]
Hi @leonovk, thanks for keeping this repo up.
I am currently using this repo for a project where I need multiple devices to connect to my VPN.
As 255 devices may be too low sometimes, is there a way that you could integrate a flexible way to change the maximum devices allowed?
As far as I can see, the alternative is to modify the WireGuard config in the image.
Thanks for you help 💯

**Comment by leonovk** [comment]
hi @BeppeMarnell this might help you https://github.com/leonovk/wg-rest-api/issues/70

**Comment by BeppeMarnell** [comment]
@leonovk Uhh yeah sorry, I misinterpreted that conversation then. Thanks!
